### ISSUE TITLE
Colocar estilo de botão em "declamar outra poesia"

### ISSUE THREAD

**Issue by DouglasFeliphe** [IgorRozani/filosofunk#108]

**Comment by aleoof** [comment]
Vou fazer isso

**Comment by aleoof** [comment]
cara eu estava vendo aqui o site de voces ficou com um tamanho muito pequeno todo ele, isso está certo ??

**Comment by DouglasFeliphe** [comment]
pensei em um botão tipo assim (só como ideia inicial):

![a](https://user-images.githubusercontent.com/28652407/66702755-7a96a300-ece1-11e9-8138-606e04d724c6.png)

**Comment by andrehgdias** [comment]
Posso colocar uma animação e talvez mudar o estilo desse botão? Para indicar que da para clicar alí, ta meio confuso tlg?

**Comment by andrehgdias** [comment]
Tá ai, fiz um estilo bem simples. 
![image](https://user-images.githubusercontent.com/44059355/67895384-22f99380-fb39-11e9-89dd-adfc0be2a36a.png)

**Comment by jarodsim** [comment]
> Tá ai, fiz um estilo bem simples. As cores são invertidas ao colocar o mouse em cima, PR: #166
> ![image](https://user-images.githubusercontent.com/44059355/67895384-22f99380-fb39-11e9-89dd-adfc0be2a36a.png)

Acho melhor usar a cor vermelha para acompanhar o estilo dos botões de player

**Comment by andrehgdias** [comment]
> > Tá ai, fiz um estilo bem simples. As cores são invertidas ao colocar o mouse em cima, PR: #166
> > ![image](https://user-images.githubusercontent.com/44059355/67895384-22f99380-fb39-11e9-89dd-adfc0be2a36a.png)
> 
> Acho melhor usar a cor vermelha para acompanhar o estilo dos botões de player
Mative a cor que já está sendo usada, mas assim que der eu altero e vejo se fica ok, se o PR fosse aceito seria melhor, já faz um tempo desde que enviei
