### ISSUE TITLE
Tocar som

### ISSUE THREAD

**Issue by FelipeZini** [IgorRozani/filosofunk#11]
Ter referência da música no youtube no tempo correto onde a frase é declamada.
Tocar de fundo e/ou opção da pessoa clicar em ouvir.

**Comment by IgorRozani** [comment]
Boa ideia!
Acredito que poderíamos fazer algo simples, colocar apenas um link na página para abrir uma nova janela com a música ou clipe.
Isso envolveria uma mudança no json para armazenar o link e um botão novo na tela.

**Comment by giancarlopro** [comment]
Tem como fazer um playback do vídeo do youtube em um iframe invisível e por pra começar no momento da frase e deixar tocando em loop, só que quando reinicia o vídeo ele começa do início.

se puder olhar o branch playback no meu fork eu fiz um protótipo, ele da play na musica do mc gorilla - cheio de sal, dai é só adaptar, colocar as chaves do id e start no json.

devo fazer um pull request?

**Comment by IgorRozani** [comment]
Caramba! Ficou muito bom! Pode fazer o PR sim @giancarlopro .
