### ISSUE TITLE
Atualizando poesias

### ISSUE THREAD

**Issue by jhonatasmatos** [IgorRozani/filosofunk#201]
Olá ,
Tentei rodar algumas poesias na aplicação e elas ficam travadas (não tocam), entao fui verificar alguns links e , ou foram removidos ou censurados.
Então estou atualizando e removendo os que não existem mais.

Posso submeter uma PR com essas alterações ?

**Comment by IgorRozani** [comment]
sim claro, muito obrigado pela revisão =)

**Comment by jhonatasmatos** [comment]
Só estou terminando.
Estou na metade do arquivo .json
Só vim verificar antes se poderia submeter uma PR .

Parabéns pelo projeto , dei muita risada hahaha
