### ISSUE TITLE
Audio não toca a primeira vez que acessa o site

### ISSUE THREAD

**Issue by IgorRozani** [IgorRozani/filosofunk#58]
Quando acessa pela primeira vez o site, o áudio não toca.

Isso ocorre apenas no primeiro acesso ao site, depois as músicas tocam normalmente.
Se acessar o site pela primeira vez, clicar no botão de stop e depois play, a música começa a tocar.

**Comment by klauskpm** [comment]
Posso pegar essa issue?

**Comment by IgorRozani** [comment]
claro =)

**Comment by klauskpm** [comment]
Achei a razão do problema. [O Google fez mudanças nas políticas de autoplay de videos deles](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), e agora os vídeos só podem tocar automaticamente após uma iteração (clique) do usuário na página, ou quando recarregam a página.

Fiz o teste colocando a própria tag deles na página, e ela não começava a tocar, só no recarregamento. Ela também tocava na primeira vez se eu clicasse rápido na página.

Se quiser, eu tenho uma sugestão de como abordar isso. Ela seria deixar o vídeo pausado inicialmente, e deixar o usuário dar o play. Até deixar o state do play salvo no SessionStorage para, ao recarregar a página, manter o state do play/pause. O que acha?
